package:
  name: nilmtk
  version: v0.3.alpha

source:
  git_tag: v0.3.alpha
  git_url: https://github.com/nilmtk/nilmtk.git

requirements:
  build:
    - python
    - pandas
    - pyyaml
    #- nilm_metadata # Local recipe
    - setuptools

  run:
    - python
    - numpy
    - scipy
    - ipython
    - matplotlib
    - pyyaml
    - pandas >=0.13
    - cython ==0.19.1
    - scikit-learn >=0.14
    - numexpr
    - mysql-python
    #- nilm_metadata
    - networkx
    - pytables
    - nose
    - psycopg2
    - coverage
    - dateutil
    - pip
    - six
    # Local recipes
    - hmmlearn
    - python-coveralls
    - graphviz
    - pygraphviz
    - sh


test:
  commands:
    - nosetests --with-coverage
  imports:
    #- nilmtk
    #- nilm_metadata
    - hmmlearn
    #- graphviz
    - pygraphviz
    - sh

about:
  home: http://nilmtk.github.io/
  summary: "NILMTK is an Open source Non-intrusive load monitoring toolkit."
