package:
  name: nilmtk
  version: 0.3.alpha

source:
  git_url: https://github.com/nilmtk/nilmtk.git
  # git_tag: 0.3.alpha ## Error in recognizing tag.

requirements:
  build:
    - python
    - nilm_metadata # Local recipe
    - setuptools

  run:
    - python
    - numpy
    - scipy
    - ipython
    - matplotlib
    - pandas >=0.13
    - cython ==0.19.1
    - scikit-learn >=0.14
    - numexpr
    - mysql-python
    - nilm_metadata
    - networkx
    - pytables
    - nose
    - psycopg2
    - coverage
    - dateutil
    - pip
    - six
    # Local recipes
    - hmmlearn
    - python-coveralls
    # - graphviz


test:
  imports:
    - nilmtk
    - nilm_metadata
    - hmmlearn

about:
  home: http://nilmtk.github.io/
  summary: "NILMTK is an Open source Non-intrusive load monitoring toolkit."
